DEFAULT_BLUEPRINT_VERSION = "1.0"
DEFAULT_CONFIDENCE = 0.5
DEFAULT_BUSINESS_SUMMARY = ""
DEFAULT_BUSINESS_MODEL = ""
DEFAULT_VALUE_CREATION = ""
DEFAULT_COMPETITIVE_POSITION = ""

DEFAULT_REASONING_TEXT = ""
